source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "webrick", "~> 1.7"

# Temas - descomenta el que prefieras usar
# gem "minima", "~> 2.5"
gem "just-the-docs"

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
end

# Windows e ingeniería específica
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end